version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: my_nginx
    ports:
      - '8000:8000'
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: my_app
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/src
    expose:
      - '8000'
    links:
      - redis
  db:
    image: postgres:11.4
    container_name: my_db
  redis:
    image: redis:4.0.14
    container_name: my_redis
    ports:
      - '6379:6379'
